version: "3.5"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tbcounter
    networks:
      - backend
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - backend
    restart: always

  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - backend
      - mongo_network
    env_file:
      - .env


  redis:
    image: redis
    restart: always
    networks:
      - backend
      - redis_network
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight
    ports:
      - 5540:5540
    networks:
      - redis_network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD}
    ports:
      - 27017:27017
    networks:
      - mongo_network
    restart: always

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:5051:8081"
    networks:
      - mongo_network
    depends_on:
      - mongo
 

networks:
  backend:
    driver: bridge
  mongo_network:
    driver: bridge
  redis_network:
    driver: bridge
